# 데이터베이스 설정
database:
  username: admin
  password: gAAAAABnyPlg_KYLvZpxnaC9MA0wFLjvD6UUo0SxvRMm4pGayDrlu0zM6O6ygRR2ftNTmVv8kruqsBh3C_IDECsJt7ssXTj_Jg==
  host: db.example.com
  port: 5432
  name: myapp_db

# API 설정
api:
  secret_key: gAAAAABl9uxXQJGvKPZwCXH7vDzE_example_encrypted_value_2  # 실제 암호화된 값으로 교체 필요
  endpoint: https://api.example.com
  timeout: 30
